import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiPrisma,
  SiMongodb,
  SiFirebase,
  SiNodedotjs,
  SiExpress,
  SiPostgresql,
  SiCss3,
  SiHtml5,
  SiJavascript,
  SiJsonwebtokens,
  SiMysql,
  SiNestjs,
  SiSocketdotio,
  SiJest,
} from "react-icons/si";
import { Project, Technology } from "@/components/sections/Projects";

// Technology badge visible in ProjectCard
export const techStack: Record<string, Technology> = {
  react: { name: "React", icon: SiReact, color: "#61DAFB" },
  next: {
    name: "Next.js",
    icon: SiNextdotjs,
    color: "#64748b",
    textColor: "#ffffff",
  },
  typescript: { name: "TypeScript", icon: SiTypescript, color: "#3178C6" },
  tailwind: { name: "Tailwind", icon: SiTailwindcss, color: "#06B6D4" },
  prisma: {
    name: "Prisma",
    icon: SiPrisma,
    color: "#5a67d8",
    textColor: "#ffffff",
  },
  mongodb: { name: "MongoDB", icon: SiMongodb, color: "#47A248" },
  firebase: { name: "Firebase", icon: SiFirebase, color: "#FFCA28" },
  node: { name: "Node.js", icon: SiNodedotjs, color: "#339933" },
  express: {
    name: "Express",
    icon: SiExpress,
    color: "#64748b",
    textColor: "#ffffff",
  },
  postgresql: { name: "PostgreSQL", icon: SiPostgresql, color: "#4169E1" },
  javascript: { name: "JavaScript", icon: SiJavascript, color: "#F7DF1E" },
  nestjs: { name: "Nest.js", icon: SiNestjs, color: "#E0234E" },
  jwt: {
    name: "JWT",
    icon: SiJsonwebtokens,
    color: "#000000",
    textColor: "#ffffff",
  },
  mysql: { name: "MySQL", icon: SiMysql, color: "#4479A1" },
  websocket: {
    name: "WebSocket",
    icon: SiSocketdotio,
    color: "#25c2a0",
    textColor: "#25c2a0",
  },
  css: { name: "CSS", icon: SiCss3, color: "#1572B6" },
  html: { name: "HTML", icon: SiHtml5, color: "#E34F26" },
  jest: { name: "Jest", icon: SiJest, color: "#C21325" },
};

export const projects: Project[] = [
  {
    id: "portfolio-windows-11",
    title: "Portfolio Windows 11",
    cover: "/assets/images/projects/portfolio-windows-11/desktop.png",
    desc: "Windows 11 Portfolio est une réplique web interactive de l'interface Windows 11, conçue pour servir de portfolio créatif. Ce projet repousse les limites de l'expérience utilisateur classique en transformant un environnement familier - celui de Windows 11 - en une vitrine innovante de compétences en développement web. Le portfolio permet d'ouvrir différentes applications et de manipuler les fenêtres exactement comme sur Windows 11, avec la possibilité de les redimensionner, les déplacer et les organiser à votre guise. N'hésitez pas à explorer cet environnement familier et à interagir avec les différentes applications pour découvrir mes réalisations !",
    screenshots: [
      "/assets/images/projects/portfolio-windows-11/desktop.png",
      "/assets/images/projects/portfolio-windows-11/terminal.png",
      "/assets/images/projects/portfolio-windows-11/dark-mode.png",
      "/assets/images/projects/portfolio-windows-11/launch-menu.png",
      "/assets/images/projects/portfolio-windows-11/explorer.png",
      "/assets/images/projects/portfolio-windows-11/chrome.png",
      "/assets/images/projects/portfolio-windows-11/audio-controls.png",
    ],
    technologies: [
      techStack.next,
      techStack.typescript,
      techStack.tailwind,
      techStack.mongodb,
    ],
    demoLink: "https://windows.estrine-alexis.fr",
    githubRepoLink: "https://github.com/iSayZ/Windows-Portfolio",
    isInConstruction: false,
    date: "Janvier 2025",
  },
  {
    id: "dashboard-haute-securite",
    title: "Dashboard de haute sécurité",
    cover: "/assets/images/projects/dashboard-haute-securite/index.png",
    desc: "Mon projet de Dashboard de haute sécurité est une plateforme adaptable, conçue pour gérer le contenu sur plusieurs sites. Entièrement développé de manière autonome, ce dashboard intègre une authentification avancée (sessions sécurisées, tokens de rafraîchissement, 2FA) et permet de créer, éditer, et organiser des articles en toute simplicité. Il est également relié à Google Analytics pour un suivi précis des visites et des statistiques, offrant une interface réactive, responsive et sécurisée pour une gestion optimale du contenu et des performances du site.",
    screenshots: [
      "/assets/images/projects/dashboard-haute-securite/index.png",
      "/assets/images/projects/dashboard-haute-securite/index-dark.png",
      "/assets/images/projects/dashboard-haute-securite/2fa.png",
      "/assets/images/projects/dashboard-haute-securite/table-article.png",
      "/assets/images/projects/dashboard-haute-securite/add-article.png",
      "/assets/images/projects/dashboard-haute-securite/order.png",
    ],
    technologies: [
      techStack.next,
      techStack.nestjs,
      techStack.typescript,
      techStack.mongodb,
      techStack.jwt,
    ],
    githubRepoLink: "https://github.com/iSayZ/Dashboard-Nest.js-Next.js",
    isInConstruction: false,
    date: "Septembre 2024",
  },
  {
    id: "crumble",
    title: "Crumble",
    cover: "/assets/images/projects/crumble/index.png",
    desc: "Crumble est un réseau social inspiré de Facebook, que j'ai développé seul, avec un fort accent sur l'interactivité et la réactivité. Ce projet intègre des fonctionnalités d'authentification sécurisée avec JWT, une gestion complète des profils utilisateurs, ainsi qu'un système de messagerie instantanée via WebSocket. Les utilisateurs peuvent publier du contenu, commenter, liker, et gérer leurs amis, le tout dans une interface réactive et responsive. J'ai également mis en place un panneau d'administration pour la gestion des utilisateurs et des publications.",
    screenshots: [
      "/assets/images/projects/crumble/login.png",
      "/assets/images/projects/crumble/index.png",
      "/assets/images/projects/crumble/profile.png",
      "/assets/images/projects/crumble/friend.png",
      "/assets/images/projects/crumble/chat.png",
      "/assets/images/projects/crumble/notification.png",
    ],
    technologies: [
      techStack.react,
      techStack.javascript,
      techStack.express,
      techStack.mysql,
      techStack.websocket,
      techStack.jwt,
    ],
    videoDemoLink: "1jPhKJag0I3d0YolTqbz-PhtQclcNMgrf",
    githubRepoLink: "https://github.com/iSayZ/Crumble",
    isInConstruction: false,
    date: "Septembre 2024",
  },
  {
    id: "spot-lille-art",
    title: "Spot Lille Art",
    cover: "/assets/images/projects/spot-lille-art/artworks.png",
    desc: "Spot Lille Art est une plateforme participative permettant de référencer, partager et découvrir des œuvres de street art dans la Métropole Européenne de Lille. Ce projet inclut un système de gestion des œuvres via une API connectée à une base de données MySQL. Les utilisateurs peuvent prendre des photos des oeuvres et renseigner leurs informations. Le site propose également un espace administrateur pour gérer les œuvres soumises, les utilisateurs, les signalements d'œuvres recouvertes ainsi que les statistiques globales de l'application.",
    screenshots: [
      "/assets/images/projects/spot-lille-art/artworks.png",
      "/assets/images/projects/spot-lille-art/artwork.png",
      "/assets/images/projects/spot-lille-art/map.png",
      "/assets/images/projects/spot-lille-art/register.png",
      "/assets/images/projects/spot-lille-art/profil.png",
    ],
    technologies: [
      techStack.react,
      techStack.javascript,
      techStack.express,
      techStack.mysql,
      techStack.jwt,
    ],
    demoLink: "https://spot-lille-art.utopland.net",
    githubRepoLink: "https://github.com/iSayZ/Spot-Lille-Art",
    isInConstruction: false,
    date: "Juillet 2024",
  },
  {
    id: "mineguide",
    title: "MineGuide",
    cover: "/assets/images/projects/mineguide/card.png",
    desc: "Site réalisé en équipe lors de l'événement 'ProtoJam' de la Wild Code School, un concours où nous avions 24 heures pour développer un site autour du thème 'Nature & Déconnexion'. Nous avons choisi de prendre le sujet à l'envers. En hommage à la période du Covid où nous nous sommes évadés à travers les jeux vidéo, nous avons choisi Minecraft ! Ce jeu emblématique nous plonge dans des environnements naturels tout en nous offrant une évasion totale de la réalité. Ce site est donc une expérience fictive où vous pouvez découvrir 4 biomes de Minecraft, où chaque membre de notre équipe propose une location de gîte. Ce projet a non seulement été un plaisir à créer, mais il a également été récompensé par le prix de la meilleure technique lors de l'événement ! 🏆 (Le site est optimisé uniquement pour les ordinateurs en raison de contraintes de temps)",
    screenshots: [
      "/assets/images/projects/mineguide/accueil.png",
      "/assets/images/projects/mineguide/aquatique.png",
      "/assets/images/projects/mineguide/avatar.png",
      "/assets/images/projects/mineguide/house.png",
      "/assets/images/projects/mineguide/monstres.png",
      "/assets/images/projects/mineguide/plantes.png",
      "/assets/images/projects/mineguide/equipe.png",
    ],
    technologies: [techStack.react, techStack.javascript, techStack.css],
    demoLink: "https://mineguide.vercel.app/",
    githubRepoLink: "https://github.com/iSayZ/MineGuide-ProtoJam2024",
    isInConstruction: false,
    date: "Mai 2024",
  },
  {
    id: "feet-n-fun",
    title: "Feet & Fun",
    cover: "/assets/images/projects/feet-n-fun/shop.png",
    desc: "Feet & Fun est un site de e-commerce (basé sur la vente de chausettes 🧦) réalisé en équipe. Nous avons créé notre propre API qui contient toutes les informations de nos 150 produits. Liste des fonctionnalités : - Panier / Liste de favoris, - Fonction de recherche (nom / description / mot clé), - Filtre (prix / tailles / couleurs), - Tri (prix coissant / décroissant / nouveautés), - Entièrement responsive",
    screenshots: [
      "/assets/images/projects/feet-n-fun/shop.png",
      "/assets/images/projects/feet-n-fun/product_details.png",
      "/assets/images/projects/feet-n-fun/search.png",
      "/assets/images/projects/feet-n-fun/filter.png",
      "/assets/images/projects/feet-n-fun/cart.png",
      "/assets/images/projects/feet-n-fun/favorites.png",
    ],
    technologies: [techStack.react, techStack.javascript, techStack.css],
    demoLink: "https://feet-n-fun.vercel.app/",
    videoDemoLink: "1Gv6c8CJhwKkj04s0U8DzqYdQmTMVIQSq",
    githubRepoLink: "https://github.com/iSayZ/Feet-Fun",
    isInConstruction: false,
    date: "Avril 2024",
  },
  {
    id: "portfolio-v1",
    title: "Portfolio v1",
    cover: "/assets/images/projects/portfolio-v1/accueil.png",
    desc: "Un portfolio minimaliste développé en React et stylisé avec Tailwind CSS, présentant mes projets et compétences en tant que développeur web. Cette interface épurée permet une navigation fluide à travers mes différentes réalisations, tout en offrant une expérience utilisateur optimisée. Un projet qui m'a permis de mettre en pratique mes connaissances en développement frontend et de créer une vitrine professionnelle pour mon travail.",
    screenshots: ["/assets/images/projects/portfolio-v1/accueil.png"],
    technologies: [techStack.react, techStack.javascript, techStack.tailwind],
    demoLink: "https://portfolio-v1.estrine-alexis.fr",
    githubRepoLink: "https://github.com/iSayZ/Portfolio",
    isInConstruction: false,
    date: "Mai 2024",
  },
  {
    id: "trombinoscope",
    title: "Trombinoscope",
    cover: "/assets/images/projects/trombinoscope/card.png",
    desc: "Trombinoscope réalisé en équipe, mettant en valeur la promotion de la Wild Code School 2024. Chaque étudiant est représenté par une carte personnalisée affichant sa photo, son âge, son nom, ses hobbies ainsi que ses liens vers LinkedIn et GitHub. Cette interface interactive permet de découvrir rapidement le profil de chaque membre de la promotion.",
    screenshots: [
      "/assets/images/projects/trombinoscope/index.png",
      "/assets/images/projects/trombinoscope/section.png",
      "/assets/images/projects/trombinoscope/card.png",
    ],
    technologies: [techStack.javascript, techStack.html, techStack.css],
    demoLink: "https://trombi-wcs.vercel.app/",
    videoDemoLink: "1FMgqABgX4yFv9QE3SsADEpWq9_qu-BIy",
    githubRepoLink: "https://github.com/iSayZ/Trombinoscope-WCS",
    isInConstruction: false,
    date: "Mars 2024",
  },
];
